s=set()
n1=input("Enter no 1:")
s.add(int(n1))
n2=input("Enter no 2:")
s.add(int(n2))
n3=input("Enter no 3:")
s.add(int(n3))
n4=input("Enter no 4:")
s.add(int(n4))
n5=input("Enter no 5:")
s.add(int(n5))
n6=input("Enter no 6:")
s.add(int(n6))
n7=input("Enter no 7:")
s.add(int(n7))
print(s)